// src/components/PromptPage.vue
<template>
  <div class="prompt-page">
    <header class="prompt-header">
      <div class="header-left">
        <div class="brand">
          <div class="brand-icon">A</div>
          <span class="brand-name">AMICUS</span>
        </div>
      </div>
      <div class="header-right">
        <button class="btn-back" @click="$router.push({ path: '/dashboard', query: { email } })">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="15 18 9 12 15 6"/></svg>
          Back to Dashboard
        </button>
      </div>
    </header>

    <main class="prompt-main">
      <div class="prompt-card">
        <div class="prompt-icon">
          <svg viewBox="0 0 24 24" width="32" height="32" fill="none" stroke="#0078D4" stroke-width="1.5">
            <path d="M12 2L2 7l10 5 10-5-10-5z"/>
            <path d="M2 17l10 5 10-5"/>
            <path d="M2 12l10 5 10-5"/>
          </svg>
        </div>
        <h1>What matters tomorrow?</h1>
        <p class="prompt-subtitle">Add today's priorities, keep permanent ones, or both. At least one is required.</p>

        <section class="prompt-section">
          <h3 class="section-title">Today's note</h3>
          <p class="section-desc">Type freely — one line per priority. Saved items join today's list below.</p>
          <textarea
            v-model="prioritiesText"
            class="priority-textarea"
            rows="7"
            placeholder="e.g. Follow up with contractor about permits&#10;Review budget for Phase 2&#10;Call insurance agent about the claim"
          ></textarea>
        </section>

        <section class="prompt-section">
          <h3 class="section-title">Today's priorities</h3>
          <p class="section-desc">Set for the next few days, then they expire on their own.</p>
          <div v-if="dailyPriorities.length > 0" class="list-block">
            <div v-for="p in dailyPriorities" :key="p.id" class="list-row">
              <span class="list-text">{{ p.rawText }}</span>
              <span class="priority-expires">{{ formatExpiry(p.expiresAt) }}</span>
              <div class="list-actions">
                <button class="btn-mini btn-danger" @click="removeDaily(p.id)">Remove</button>
              </div>
            </div>
          </div>
          <p v-else class="empty-note">No daily priorities yet.</p>
        </section>

        <section class="prompt-section">
          <h3 class="section-title">Permanent priorities</h3>
          <p class="section-desc">Always-on. Never expire, always used to spot relevant emails.</p>
          <div v-if="permanentPriorities.length > 0" class="list-block">
            <div v-for="p in permanentPriorities" :key="p.id" class="list-row">
              <input
                v-if="editingId === p.id"
                v-model="editingText"
                class="list-input"
                @keyup.enter="savePermanentEdit(p.id)"
              />
              <span v-else class="list-text">{{ p.rawText }}</span>
              <div class="list-actions">
                <button v-if="editingId === p.id" class="btn-mini btn-save" @click="savePermanentEdit(p.id)">Save</button>
                <button v-else class="btn-mini" @click="startPermanentEdit(p)">Edit</button>
                <button class="btn-mini btn-danger" @click="removePermanent(p.id)">Remove</button>
              </div>
            </div>
          </div>
          <p v-else class="empty-note">No permanent priorities yet.</p>
          <div class="add-row">
            <input
              v-model="newPermanent"
              class="list-input"
              placeholder="e.g. Keep an eye on the bank loan"
              @keyup.enter="addPermanent"
            />
            <button class="btn-add-item" @click="addPermanent" :disabled="!newPermanent.trim()">Add</button>
          </div>
        </section>

        <button class="btn btn-primary" @click="handleSubmit" :disabled="loading || !hasPriorities">
          {{ loading ? 'Saving...' : 'Save' }}
        </button>

        <p v-if="message" class="message" :class="{ error: isError }">{{ message }}</p>
      </div>
    </main>
  </div>
</template>

<script>
import {
  getDailyPriorities,
  getPermanentPriorities,
  savePriorities,
  addPermanentPriority,
  updatePermanentPriority,
  deletePermanentPriority,
  deletePriority,
} from '../api.js'

export default {
  name: 'PromptPage',
  data() {
    return {
      prioritiesText: '',
      dailyPriorities: [],
      permanentPriorities: [],
      newPermanent: '',
      editingId: null,
      editingText: '',
      loading: false,
      message: '',
      isError: false,
    }
  },
  computed: {
    email() { return this.$route.query.email || '' },
    hasPriorities() {
      const hasText = this.prioritiesText.split('\n').some((l) => l.trim())
      return hasText || this.dailyPriorities.length > 0 || this.permanentPriorities.length > 0
    },
  },
  mounted() {
    if (!this.email) {
      this.$router.push('/login')
      return
    }
    this.loadAll()
  },
  methods: {
    async loadAll() {
      try {
        const [daily, permanent] = await Promise.all([
          getDailyPriorities(this.email),
          getPermanentPriorities(this.email),
        ])
        this.dailyPriorities = daily
        this.permanentPriorities = permanent
      } catch (e) {
        console.error('Failed to load priorities:', e)
      }
    },
    async handleSubmit() {
      this.loading = true
      this.message = ''
      this.isError = false
      try {
        const filled = this.prioritiesText
          .split('\n')
          .map((l) => l.trim())
          .filter(Boolean)
        if (filled.length > 0) {
          await savePriorities(this.email, filled)
        }
        this.prioritiesText = ''
        await this.loadAll()
        this.message = 'Saved!'
      } catch (e) {
        this.message = e.message || 'Failed to save'
        this.isError = true
      } finally {
        this.loading = false
      }
    },
    async removeDaily(id) {
      try {
        await deletePriority(this.email, id)
        await this.loadAll()
      } catch (e) {
        this.message = e.message || 'Failed to remove priority'
        this.isError = true
      }
    },
    startPermanentEdit(p) {
      this.editingId = p.id
      this.editingText = p.rawText
    },
    async savePermanentEdit(id) {
      const text = this.editingText.trim()
      if (!text) return
      try {
        await updatePermanentPriority(this.email, id, text)
        this.editingId = null
        this.editingText = ''
        await this.loadAll()
      } catch (e) {
        this.message = e.message || 'Failed to update priority'
        this.isError = true
      }
    },
    async addPermanent() {
      const text = this.newPermanent.trim()
      if (!text) return
      try {
        await addPermanentPriority(this.email, text)
        this.newPermanent = ''
        await this.loadAll()
      } catch (e) {
        this.message = e.message || 'Failed to add priority'
        this.isError = true
      }
    },
    async removePermanent(id) {
      try {
        await deletePermanentPriority(this.email, id)
        await this.loadAll()
      } catch (e) {
        this.message = e.message || 'Failed to remove priority'
        this.isError = true
      }
    },
    formatExpiry(dateStr) {
      if (!dateStr) return 'permanent'
      const date = new Date(dateStr)
      const now = new Date()
      const diffDays = Math.ceil((date - now) / (1000 * 60 * 60 * 24))
      if (diffDays <= 0) return 'today'
      if (diffDays === 1) return 'tomorrow'
      return `in ${diffDays} days`
    },
  },
}
</script>

<style scoped>
.prompt-page { min-height: 100vh; min-height: 100dvh; background: #f8fafc; }

.prompt-header {
  background: #fff; border-bottom: 1px solid #e2e8f0;
  padding: 0 12px; height: 56px;
  display: flex; align-items: center; justify-content: space-between;
}
.header-left { display: flex; align-items: center; gap: 12px; }
.brand { display: flex; align-items: center; gap: 8px; }
.brand-icon {
  width: 30px; height: 30px; border-radius: 8px;
  background: linear-gradient(135deg, #0078D4, #6C5CE7);
  color: #fff; display: flex; align-items: center; justify-content: center;
  font-size: 14px; font-weight: 800;
}
.brand-name {
  font-size: 15px; font-weight: 800; letter-spacing: -0.3px;
  background: linear-gradient(135deg, #0078D4, #6C5CE7);
  -webkit-background-clip: text; -webkit-text-fill-color: transparent;
}
.btn-back {
  display: flex; align-items: center; gap: 5px;
  padding: 6px 10px; border-radius: 8px; border: 1px solid #e2e8f0;
  background: #fff; color: #475569; font-size: 12px; font-weight: 500;
  cursor: pointer; transition: all 0.15s; min-height: 36px;
}
.btn-back:hover { background: #f1f5f9; }

.prompt-main { max-width: 700px; margin: 0 auto; padding: 20px 16px 48px; }
.prompt-title { font-size: 20px; font-weight: 700; color: #0f172a; margin: 0 0 6px; }
.prompt-desc { font-size: 13px; color: #64748b; margin: 0 0 24px; line-height: 1.5; }

.prompt-card {
  background: #fff; border-radius: 12px; padding: 20px;
  border: 1px solid #e2e8f0; margin-bottom: 20px;
}
.prompt-card h2 { font-size: 15px; font-weight: 700; color: #0f172a; margin: 0 0 4px; }
.card-desc { font-size: 12px; color: #64748b; margin: 0 0 16px; }

.priorities-list { display: flex; flex-direction: column; gap: 8px; margin-bottom: 16px; }
.priority-row {
  display: flex; align-items: center; justify-content: space-between; gap: 10px;
  padding: 10px 12px; background: #f8fafc; border-radius: 8px;
}
.priority-text { font-size: 13px; color: #0f172a; font-weight: 500; flex: 1; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.priority-input {
  flex: 1; padding: 10px 12px; border: 1px solid #e2e8f0; border-radius: 8px;
  font-size: 13px; color: #0f172a; outline: none; min-width: 0;
}
.priority-input:focus { border-color: #0078D4; box-shadow: 0 0 0 3px rgba(0,120,212,0.1); }
.priority-actions { display: flex; align-items: center; gap: 4px; flex-shrink: 0; }

.btn-mini {
  padding: 5px 10px; border-radius: 6px; font-size: 11px; font-weight: 600;
  border: 1px solid #e2e8f0; background: #fff; color: #475569; cursor: pointer;
  transition: all 0.15s;
}
.btn-mini:hover { background: #f1f5f9; }
.btn-save { background: #0078D4; color: #fff; border-color: #0078D4; }
.btn-save:hover { background: #005a9e; }
.btn-danger { color: #dc2626; border-color: #fca5a5; background: #fef2f2; }
.btn-danger:hover { background: #fee2e2; }

.add-row { display: flex; align-items: center; gap: 8px; }
.btn-add-priority {
  padding: 10px 16px; border-radius: 8px; font-size: 13px; font-weight: 600;
  border: none; background: #0078D4; color: #fff; cursor: pointer; flex-shrink: 0;
  transition: all 0.15s; min-height: 40px;
}
.btn-add-priority:hover:not(:disabled) { background: #005a9e; }
.btn-add-priority:disabled { background: #94a3b8; cursor: not-allowed; }

.empty-note { font-size: 12px; color: #94a3b8; margin: 0 0 16px; font-style: italic; }

.btn {
  width: 100%; padding: 12px; border-radius: 8px; font-size: 14px; font-weight: 600;
  cursor: pointer; border: none; transition: all 0.15s; min-height: 44px;
}
.btn-primary { background: #0078D4; color: #fff; box-shadow: 0 2px 8px rgba(0,120,212,0.3); }
.btn-primary:hover:not(:disabled) { background: #005a9e; }
.btn-primary:disabled { background: #94a3b8; cursor: not-allowed; }

.message { font-size: 12px; margin-top: 10px; text-align: center; color: #059669; }
.message.error { color: #dc2626; }

@media (min-width: 768px) {
  .prompt-header { padding: 0 24px; height: 60px; }
  .brand-icon { width: 32px; height: 32px; font-size: 15px; }
  .brand-name { font-size: 16px; }
  .btn-back { padding: 7px 14px; font-size: 13px; }
  .prompt-main { padding: 32px 24px 48px; }
  .prompt-title { font-size: 24px; }
  .prompt-desc { font-size: 14px; }
  .prompt-card { padding: 24px; }
}
</style>

// src/pages/PromptPage.tsx
import { useState, useEffect } from 'react';
import { Layers, Plus, Pencil, Trash2, Save } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { useAuth } from '@/hooks/useAuth';
import {
  getDailyPriorities,
  getPermanentPriorities,
  savePriorities,
  addPermanentPriority,
  updatePermanentPriority,
  deletePermanentPriority,
  deletePriority,
} from '@/lib/api';
import type { Priority } from '@/types';

export function PromptPage() {
  const { email } = useAuth();

  const [prioritiesText, setPrioritiesText] = useState('');
  const [dailyPriorities, setDailyPriorities] = useState<Priority[]>([]);
  const [permanentPriorities, setPermanentPriorities] = useState<Priority[]>([]);

  const [newPermanent, setNewPermanent] = useState('');
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editingText, setEditingText] = useState('');

  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [isError, setIsError] = useState(false);

  useEffect(() => {
    if (!email) return;

    Promise.all([
      getDailyPriorities(email),
      getPermanentPriorities(email),
    ]).then(([daily, permanent]) => {
      setDailyPriorities(daily);
      setPermanentPriorities(permanent);
    }).catch(console.error).finally(() => setLoading(false));
  }, [email]);

  const hasPriorities = prioritiesText.split('\n').some((l) => l.trim()) ||
    dailyPriorities.length > 0 ||
    permanentPriorities.length > 0;

  const handleSave = async () => {
    if (!email) return;

    setSaving(true);
    setMessage('');
    setIsError(false);

    try {
      const filled = prioritiesText
        .split('\n')
        .map((l) => l.trim())
        .filter(Boolean);

      if (filled.length > 0) {
        await savePriorities(email, filled);
      }

      setPrioritiesText('');
      const [daily, permanent] = await Promise.all([
        getDailyPriorities(email),
        getPermanentPriorities(email),
      ]);
      setDailyPriorities(daily);
      setPermanentPriorities(permanent);
      setMessage('Saved!');
    } catch (e) {
      setMessage(e instanceof Error ? e.message : 'Failed to save');
      setIsError(true);
    } finally {
      setSaving(false);
    }
  };

  const handleRemoveDaily = async (id: string) => {
    if (!email) return;

    try {
      await deletePriority(email, id);
      const [daily, permanent] = await Promise.all([
        getDailyPriorities(email),
        getPermanentPriorities(email),
      ]);
      setDailyPriorities(daily);
      setPermanentPriorities(permanent);
    } catch (e) {
      setMessage(e instanceof Error ? e.message : 'Failed to remove');
      setIsError(true);
    }
  };

  const handleAddPermanent = async () => {
    if (!email || !newPermanent.trim()) return;

    try {
      await addPermanentPriority(email, newPermanent.trim());
      setNewPermanent('');
      const permanent = await getPermanentPriorities(email);
      setPermanentPriorities(permanent);
    } catch (e) {
      setMessage(e instanceof Error ? e.message : 'Failed to add');
      setIsError(true);
    }
  };

  const handleSavePermanentEdit = async (id: string) => {
    if (!email || !editingText.trim()) return;

    try {
      await updatePermanentPriority(email, id, editingText.trim());
      setEditingId(null);
      setEditingText('');
      const permanent = await getPermanentPriorities(email);
      setPermanentPriorities(permanent);
    } catch (e) {
      setMessage(e instanceof Error ? e.message : 'Failed to update');
      setIsError(true);
    }
  };

  const handleRemovePermanent = async (id: string) => {
    if (!email) return;

    try {
      await deletePermanentPriority(email, id);
      const permanent = await getPermanentPriorities(email);
      setPermanentPriorities(permanent);
    } catch (e) {
      setMessage(e instanceof Error ? e.message : 'Failed to remove');
      setIsError(true);
    }
  };

  const formatExpiry = (expiresAt: string | null) => {
    if (!expiresAt) return 'permanent';
    const date = new Date(expiresAt);
    const now = new Date();
    const diffDays = Math.ceil((date.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
    if (diffDays <= 0) return 'today';
    if (diffDays === 1) return 'tomorrow';
    return `in ${diffDays} days`;
  };

  if (loading) {
    return (
      <div className="max-w-2xl mx-auto py-8 px-4">
        <div className="animate-pulse space-y-6">
          <div className="h-8 bg-muted rounded w-64" />
          <div className="h-64 bg-muted rounded-xl" />
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto py-8 px-4 space-y-6">
      {/* Header */}
      <div className="text-center">
        <div className="w-16 h-16 rounded-2xl bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center mx-auto mb-4">
          <Layers className="w-8 h-8 text-blue-600" />
        </div>
        <h1 className="text-2xl font-bold text-foreground">What matters tomorrow?</h1>
        <p className="text-muted-foreground mt-1">
          Add today's priorities, keep permanent ones, or both.
        </p>
      </div>

      {/* Today's Note */}
      <Card>
        <CardHeader>
          <CardTitle>Today's note</CardTitle>
          <CardDescription>
            Type freely — one line per priority. Saved items join today's list below.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Textarea
            value={prioritiesText}
            onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setPrioritiesText(e.target.value)}
            rows={7}
            placeholder={"e.g. Follow up with contractor about permits\nReview budget for Phase 2\nCall insurance agent about the claim"}
          />
        </CardContent>
      </Card>

      {/* Today's Priorities */}
      <Card>
        <CardHeader>
          <CardTitle>Today's priorities</CardTitle>
          <CardDescription>
            Set for the next few days, then they expire on their own.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {dailyPriorities.length > 0 ? (
            <div className="space-y-2">
              {dailyPriorities.map((p) => (
                <div key={p.id} className="flex items-center gap-3 p-3 bg-muted/50 rounded-lg">
                  <span className="flex-1 text-sm">{p.rawText}</span>
                  <span className="text-xs text-muted-foreground">
                    {formatExpiry(p.expiresAt)}
                  </span>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="text-destructive hover:text-destructive"
                    onClick={() => handleRemoveDaily(p.id)}
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground italic">No daily priorities yet.</p>
          )}
        </CardContent>
      </Card>

      {/* Permanent Priorities */}
      <Card>
        <CardHeader>
          <CardTitle>Permanent priorities</CardTitle>
          <CardDescription>
            Always-on. Never expire, always used to spot relevant emails.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {permanentPriorities.length > 0 && (
            <div className="space-y-2">
              {permanentPriorities.map((p) => (
                <div key={p.id} className="flex items-center gap-2 p-3 bg-muted/50 rounded-lg">
                  {editingId === p.id ? (
                    <Input
                      value={editingText}
                      onChange={(e) => setEditingText(e.target.value)}
                      onKeyDown={(e) => e.key === 'Enter' && handleSavePermanentEdit(p.id)}
                      className="flex-1"
                      autoFocus
                    />
                  ) : (
                    <span className="flex-1 text-sm">{p.rawText}</span>
                  )}
                  <div className="flex items-center gap-1">
                    {editingId === p.id ? (
                      <Button size="sm" onClick={() => handleSavePermanentEdit(p.id)}>
                        <Save className="w-4 h-4" />
                      </Button>
                    ) : (
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => {
                          setEditingId(p.id);
                          setEditingText(p.rawText);
                        }}
                      >
                        <Pencil className="w-4 h-4" />
                      </Button>
                    )}
                    <Button
                      size="sm"
                      variant="ghost"
                      className="text-destructive hover:text-destructive"
                      onClick={() => handleRemovePermanent(p.id)}
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}

          <div className="flex gap-2">
            <Input
              placeholder="e.g. Keep an eye on the bank loan"
              value={newPermanent}
              onChange={(e) => setNewPermanent(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleAddPermanent()}
            />
            <Button onClick={handleAddPermanent} disabled={!newPermanent.trim()}>
              <Plus className="w-4 h-4 mr-1" />
              Add
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Save Button */}
      <Button
        onClick={handleSave}
        disabled={saving || !hasPriorities}
        className="w-full"
        size="lg"
      >
        <Save className="w-4 h-4 mr-2" />
        {saving ? 'Saving...' : 'Save'}
      </Button>

      {message && (
        <p className={`text-sm text-center ${isError ? 'text-destructive' : 'text-emerald-600'}`}>
          {message}
        </p>
      )}
    </div>
  );
}
