// src/components/SettingsPage.vue
<template>
  <div class="settings-page">
    <header class="settings-header">
      <div class="header-left">
        <div class="brand">
          <div class="brand-icon">A</div>
          <span class="brand-name">AMICUS</span>
        </div>
      </div>
      <div class="header-right">
        <button class="btn-back" @click="$router.push({ path: '/dashboard', query: { email } })">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="15 18 9 12 15 6"/></svg>
          Back to Dashboard
        </button>
      </div>
    </header>

    <main class="settings-main">
      <h1 class="settings-title">Settings</h1>

      <div class="settings-card">
        <h2>Digest Schedule</h2>
        <p class="section-desc">Choose when you receive your daily email summary.</p>

        <div class="field-group">
          <label class="field-label">Morning digest time</label>
          <input v-model="form.digestTime" type="time" class="time-input" />
        </div>

        <div class="field-group">
          <label class="field-label">Timezone</label>
          <select v-model="form.timezone" class="select-input">
            <option value="Europe/Lisbon">Europe/Lisbon (GMT+0/+1)</option>
            <option value="Europe/London">Europe/London (GMT+0/+1)</option>
            <option value="Europe/Paris">Europe/Paris (GMT+1/+2)</option>
            <option value="Europe/Berlin">Europe/Berlin (GMT+1/+2)</option>
            <option value="Europe/Madrid">Europe/Madrid (GMT+1/+2)</option>
            <option value="America/New_York">America/New_York (GMT-5/-4)</option>
            <option value="America/Chicago">America/Chicago (GMT-6/-5)</option>
            <option value="America/Denver">America/Denver (GMT-7/-6)</option>
            <option value="America/Los_Angeles">America/Los_Angeles (GMT-8/-7)</option>
            <option value="America/Sao_Paulo">America/Sao_Paulo (GMT-3)</option>
            <option value="America/Buenos_Aires">America/Buenos_Aires (GMT-3)</option>
            <option value="America/Santiago">America/Santiago (GMT-4/-3)</option>
            <option value="America/Bogota">America/Bogota (GMT-5)</option>
            <option value="America/Mexico_City">America/Mexico_City (GMT-6/-5)</option>
            <option value="Asia/Tokyo">Asia/Tokyo (GMT+9)</option>
            <option value="Asia/Shanghai">Asia/Shanghai (GMT+8)</option>
            <option value="Asia/Kolkata">Asia/Kolkata (GMT+5:30)</option>
            <option value="Australia/Sydney">Australia/Sydney (GMT+10/+11)</option>
          </select>
        </div>
      </div>

      <div class="settings-card">
        <h2>Daily Reminder</h2>
        <p class="section-desc">Get a reminder to set tomorrow's priorities.</p>

        <div class="toggle-row" @click="form.reminderEnabled = !form.reminderEnabled">
          <div class="toggle-info">
            <div>
              <span class="toggle-label">Enable daily reminder</span>
              <span class="toggle-desc">Receive a calendar event and/or push notification</span>
            </div>
          </div>
          <button class="toggle-switch" :class="{ on: form.reminderEnabled }" @click.stop="form.reminderEnabled = !form.reminderEnabled" type="button">
            <span class="toggle-knob"></span>
          </button>
        </div>

        <div v-if="form.reminderEnabled" class="reminder-options">
          <div class="field-group">
            <label class="field-label">Reminder time</label>
            <input v-model="form.reminderTime" type="time" class="time-input" />
          </div>

          <div class="reminder-channels">
            <h3>Notification channels</h3>

            <div class="channel-option">
              <div class="channel-info">
                <div class="channel-icon cal-icon">
                  <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg>
                </div>
                <div>
                  <span class="channel-label">Google Calendar</span>
                  <span class="channel-desc">Creates a daily calendar event</span>
                </div>
              </div>
              <a v-if="!calendarConnected" :href="calendarConnectUrl" class="btn-connect">Connect</a>
              <span v-else class="connected-badge">Connected</span>
            </div>

            <div class="channel-option">
              <div class="channel-info">
                <div class="channel-icon ics-icon">
                  <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>
                </div>
                <div>
                  <span class="channel-label">Apple Calendar / .ics</span>
                  <span class="channel-desc">Download a file to import into any calendar app</span>
                </div>
              </div>
              <a :href="icsDownloadUrl" class="btn-download" download>Download .ics</a>
            </div>

            <div class="channel-option">
              <div class="channel-info">
                <div class="channel-icon push-icon">
                  <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>
                </div>
                <div>
                  <span class="channel-label">Push Notifications</span>
                  <span class="channel-desc">Browser notification (requires PWA install on mobile)</span>
                </div>
              </div>
              <button v-if="!pushEnabled" class="btn-connect" @click="enablePush" :disabled="!pushSupported">
                {{ pushSupported ? 'Enable' : 'Not supported' }}
              </button>
              <button v-else class="btn-disconnect" @click="disablePush">Disable</button>
            </div>

            <p v-if="!pushSupported" class="push-note">Push notifications require a PWA-capable browser. On iOS, add this app to your Home Screen first.</p>
          </div>
        </div>
      </div>

      <div class="settings-card">
        <h2>Permanent Priorities</h2>
        <p class="section-desc">
          These never expire and are always used to spot relevant emails. Set them
          once and they stick around.
        </p>

        <div v-if="permanentPriorities.length > 0" class="list-block">
          <div
            v-for="p in permanentPriorities"
            :key="p.id"
            class="list-row"
          >
            <input
              v-if="editingId === p.id"
              v-model="editingText"
              class="list-input"
              @keyup.enter="savePermanentEdit(p.id)"
            />
            <span v-else class="list-text">{{ p.rawText }}</span>
            <div class="list-actions">
              <button
                v-if="editingId === p.id"
                class="btn-mini btn-save"
                @click="savePermanentEdit(p.id)"
              >
                Save
              </button>
              <button
                v-else
                class="btn-mini"
                @click="startPermanentEdit(p)"
              >
                Edit
              </button>
              <button
                class="btn-mini btn-danger"
                @click="removePermanent(p.id)"
              >
                Delete
              </button>
            </div>
          </div>
        </div>
        <p v-else class="empty-note">No permanent priorities yet.</p>

        <div class="add-row">
          <input
            v-model="newPermanent"
            class="list-input"
            placeholder="e.g. Keep an eye on the bank loan"
            @keyup.enter="addPermanent"
          />
          <button class="btn-add-item" @click="addPermanent" :disabled="!newPermanent.trim()">
            Add
          </button>
        </div>
      </div>

      <div class="settings-card">
        <h2>Important Senders</h2>
        <p class="section-desc">
          Emails from these addresses are always flagged, even if they don't match
          a daily or permanent priority.
        </p>

        <div v-if="importantSenders.length > 0" class="list-block">
          <div
            v-for="(sender, index) in importantSenders"
            :key="index"
            class="list-row"
          >
            <span class="list-text">{{ sender }}</span>
            <div class="list-actions">
              <button
                class="btn-mini btn-danger"
                @click="removeSender(index)"
              >
                Delete
              </button>
            </div>
          </div>
        </div>
        <p v-else class="empty-note">No important senders yet.</p>

        <div class="add-row">
          <input
            v-model="newSender"
            class="list-input"
            type="email"
            placeholder="name@company.com"
            @keyup.enter="addSender"
          />
          <button class="btn-add-item" @click="addSender" :disabled="!isValidSender">
            Add
          </button>
        </div>
      </div>

      <button class="btn btn-primary" @click="handleSave" :disabled="saving">
        {{ saving ? 'Saving...' : 'Save Settings' }}
      </button>

      <p v-if="message" class="message" :class="{ error: isError }">{{ message }}</p>
    </main>
  </div>
</template>

<script>
import { getUserSettings, saveUserSettings, subscribePush, unsubscribePush, getVapidPublicKey, getPermanentPriorities, addPermanentPriority, updatePermanentPriority, deletePermanentPriority } from '../api.js'

export default {
  name: 'SettingsPage',
  data() {
    return {
      form: {
        digestTime: '08:00',
        reminderTime: '18:00',
        reminderEnabled: false,
        timezone: 'Europe/Lisbon',
      },
      userId: '',
      calendarConnected: false,
      pushEnabled: false,
      pushSupported: false,
      saving: false,
      message: '',
      isError: false,
      permanentPriorities: [],
      newPermanent: '',
      editingId: null,
      editingText: '',
      importantSenders: [],
      newSender: '',
    }
  },
  computed: {
    email() { return this.$route.query.email || '' },
    calendarConnectUrl() {
      const id = this.userId || this.email
      return `${import.meta.env.VITE_API_URL || 'http://localhost:3000'}/calendar/connect/${encodeURIComponent(id)}`
    },
    icsDownloadUrl() {
      return `${import.meta.env.VITE_API_URL || 'http://localhost:3000'}/calendar/ics/${encodeURIComponent(this.email)}`
    },
    isValidSender() {
      return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(this.newSender.trim())
    },
  },
  async mounted() {
    if (!this.email) {
      this.$router.push('/login')
      return
    }

    await this.loadSettings()
    await this.loadPermanentPriorities()
    this.checkPushSupport()

    if (this.$route.query.calendar === 'connected') {
      this.calendarConnected = true
      this.message = 'Calendar connected successfully!'
      // Auto-enable the reminder toggle if it wasn't already on
      if (!this.form.reminderEnabled) {
        this.form.reminderEnabled = true
        await saveUserSettings(this.email, this.form).catch(() => {})
      }
    }
  },
  methods: {
    async loadSettings() {
      try {
        const settings = await getUserSettings(this.email)
        this.userId = settings.userId || ''
        this.form.digestTime = settings.digestTime || '08:00'
        this.form.reminderTime = settings.reminderTime || '18:00'
        this.form.reminderEnabled = settings.reminderEnabled || false
        this.form.timezone = settings.timezone || 'Europe/Lisbon'
        this.calendarConnected = settings.calendarConnected || false
        this.pushEnabled = !!settings.pushSubscription
        this.importantSenders = settings.importantSenders || []
      } catch (e) {
        console.error('Failed to load settings:', e)
      }
    },
    async loadPermanentPriorities() {
      try {
        this.permanentPriorities = await getPermanentPriorities(this.email)
      } catch (e) {
        console.error('Failed to load permanent priorities:', e)
      }
    },
    startPermanentEdit(p) {
      this.editingId = p.id
      this.editingText = p.rawText
    },
    async savePermanentEdit(id) {
      const text = this.editingText.trim()
      if (!text) return
      try {
        await updatePermanentPriority(this.email, id, text)
        this.editingId = null
        this.editingText = ''
        await this.loadPermanentPriorities()
      } catch (e) {
        this.message = e.message || 'Failed to update priority'
        this.isError = true
      }
    },
    async addPermanent() {
      const text = this.newPermanent.trim()
      if (!text) return
      try {
        await addPermanentPriority(this.email, text)
        this.newPermanent = ''
        await this.loadPermanentPriorities()
      } catch (e) {
        this.message = e.message || 'Failed to add priority'
        this.isError = true
      }
    },
    async removePermanent(id) {
      try {
        await deletePermanentPriority(this.email, id)
        await this.loadPermanentPriorities()
      } catch (e) {
        this.message = e.message || 'Failed to delete priority'
        this.isError = true
      }
    },
    addSender() {
      const v = this.newSender.trim().toLowerCase()
      if (!this.isValidSender || this.importantSenders.includes(v)) return
      this.importantSenders.push(v)
      this.newSender = ''
    },
    removeSender(index) {
      this.importantSenders.splice(index, 1)
    },
    checkPushSupport() {
      this.pushSupported = 'serviceWorker' in navigator && 'PushManager' in window && 'Notification' in window
    },
    async enablePush() {
      if (!this.pushSupported) return
      try {
        const permission = await Notification.requestPermission()
        if (permission !== 'granted') {
          this.message = 'Notification permission denied'
          this.isError = true
          return
        }

        const reg = await navigator.serviceWorker.ready
        const vapidRes = await getVapidPublicKey()
        if (!vapidRes.publicKey) {
          this.message = 'Push notifications not configured on server'
          this.isError = true
          return
        }

        const subscription = await reg.pushManager.subscribe({
          userVisibleOnly: true,
          applicationServerKey: this.urlBase64ToUint8Array(vapidRes.publicKey),
        })

        await subscribePush(this.email, subscription.toJSON())
        this.pushEnabled = true
        this.message = 'Push notifications enabled!'
        this.isError = false
      } catch (e) {
        this.message = e.message || 'Failed to enable push'
        this.isError = true
      }
    },
    async disablePush() {
      try {
        const reg = await navigator.serviceWorker.ready
        const subscription = await reg.pushManager.getSubscription()
        if (subscription) await subscription.unsubscribe()
        await unsubscribePush(this.email)
        this.pushEnabled = false
        this.message = 'Push notifications disabled'
        this.isError = false
      } catch (e) {
        console.error('Failed to disable push:', e)
      }
    },
    urlBase64ToUint8Array(base64String) {
      const padding = '='.repeat((4 - base64String.length % 4) % 4)
      const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/')
      const rawData = window.atob(base64)
      const outputArray = new Uint8Array(rawData.length)
      for (let i = 0; i < rawData.length; ++i) {
        outputArray[i] = rawData.charCodeAt(i)
      }
      return outputArray
    },
    async handleSave() {
      this.saving = true
      this.message = ''
      this.isError = false
      try {
        await saveUserSettings(this.email, {
          ...this.form,
          importantSenders: this.importantSenders,
        })
        this.message = 'Settings saved!'
        this.isError = false
      } catch (e) {
        this.message = e.message || 'Failed to save settings'
        this.isError = true
      } finally {
        this.saving = false
      }
    },
  },
}
</script>

<style scoped>
.settings-page { min-height: 100vh; background: #f8fafc; }

.settings-header {
  background: #fff; border-bottom: 1px solid #e2e8f0;
  padding: 0 32px; height: 60px;
  display: flex; align-items: center; justify-content: space-between;
}
.header-left { display: flex; align-items: center; gap: 20px; }
.brand { display: flex; align-items: center; gap: 8px; }
.brand-icon {
  width: 32px; height: 32px; border-radius: 8px;
  background: linear-gradient(135deg, #0078D4, #6C5CE7);
  color: #fff; display: flex; align-items: center; justify-content: center;
  font-size: 15px; font-weight: 800;
}
.brand-name {
  font-size: 16px; font-weight: 800; letter-spacing: -0.3px;
  background: linear-gradient(135deg, #0078D4, #6C5CE7);
  -webkit-background-clip: text; -webkit-text-fill-color: transparent;
}
.btn-back {
  display: flex; align-items: center; gap: 6px;
  padding: 7px 14px; border-radius: 8px; border: 1px solid #e2e8f0;
  background: #fff; color: #475569; font-size: 13px; font-weight: 500;
  cursor: pointer; transition: all 0.15s;
}
.btn-back:hover { background: #f1f5f9; }

.settings-main { max-width: 600px; margin: 0 auto; padding: 32px 24px; }
.settings-title { font-size: 24px; font-weight: 700; color: #0f172a; margin: 0 0 24px; }

.settings-card {
  background: #fff; border-radius: 12px; padding: 24px;
  border: 1px solid #e2e8f0; margin-bottom: 20px;
}
.settings-card h2 { font-size: 16px; font-weight: 700; color: #0f172a; margin: 0 0 4px; }
.section-desc { font-size: 13px; color: #64748b; margin: 0 0 20px; }

.field-group { margin-bottom: 16px; }
.field-label { display: block; font-size: 13px; font-weight: 600; color: #0f172a; margin-bottom: 6px; }
.time-input, .select-input {
  width: 100%; padding: 11px 12px; border: 1px solid #e2e8f0; border-radius: 8px;
  font-size: 14px; color: #0f172a; outline: none;
}
.time-input:focus, .select-input:focus {
  border-color: #0078D4; box-shadow: 0 0 0 3px rgba(0,120,212,0.1);
}

.toggle-row {
  display: flex; align-items: center; justify-content: space-between;
  padding: 16px; background: #f8fafc; border-radius: 12px; cursor: pointer;
}
.toggle-row:hover { background: #f1f5f9; }
.toggle-info { display: flex; align-items: center; gap: 12px; }
.toggle-label { font-size: 14px; font-weight: 600; color: #0f172a; display: block; }
.toggle-desc { font-size: 12px; color: #94a3b8; display: block; margin-top: 2px; }
.toggle-switch {
  width: 48px; height: 26px; border-radius: 9999px; background: #cbd5e1;
  border: none; cursor: pointer; position: relative; transition: background 0.2s; padding: 0; flex-shrink: 0;
}
.toggle-switch.on { background: #0078D4; }
.toggle-knob {
  position: absolute; top: 3px; left: 3px; width: 20px; height: 20px; border-radius: 50%;
  background: #fff; transition: transform 0.2s; box-shadow: 0 1px 3px rgba(0,0,0,0.15);
}
.toggle-switch.on .toggle-knob { transform: translateX(22px); }

.reminder-options { margin-top: 16px; }
.reminder-channels h3 {
  font-size: 13px; font-weight: 700; color: #94a3b8; text-transform: uppercase;
  letter-spacing: 0.3px; margin: 0 0 12px;
}

.channel-option {
  display: flex; align-items: center; justify-content: space-between;
  padding: 14px; background: #f8fafc; border-radius: 10px; margin-bottom: 8px;
}
.channel-info { display: flex; align-items: center; gap: 12px; }
.channel-icon {
  width: 40px; height: 40px; border-radius: 8px;
  display: flex; align-items: center; justify-content: center;
}
.cal-icon { background: #dbeafe; color: #2563eb; }
.ics-icon { background: #fef3c7; color: #d97706; }
.push-icon { background: #e0e7ff; color: #4f46e5; }
.channel-label { font-size: 14px; font-weight: 600; color: #0f172a; display: block; }
.channel-desc { font-size: 12px; color: #94a3b8; display: block; margin-top: 2px; }

.btn-connect, .btn-download {
  padding: 7px 14px; border-radius: 6px; font-size: 12px; font-weight: 600;
  text-decoration: none; cursor: pointer; border: none; transition: all 0.15s;
}
.btn-connect { background: #0078D4; color: #fff; }
.btn-connect:hover { background: #005a9e; }
.btn-connect:disabled { background: #cbd5e1; cursor: not-allowed; }
.btn-download { background: #f1f5f9; color: #475569; border: 1px solid #e2e8f0; }
.btn-download:hover { background: #e2e8f0; }
.btn-disconnect { padding: 7px 14px; border-radius: 6px; font-size: 12px; font-weight: 600; background: #fef2f2; color: #dc2626; border: 1px solid #fca5a5; cursor: pointer; }
.connected-badge { font-size: 12px; font-weight: 600; color: #059669; }

.push-note { font-size: 12px; color: #94a3b8; margin-top: 8px; font-style: italic; }

.list-block { display: flex; flex-direction: column; gap: 8px; margin-bottom: 16px; }
.list-row {
  display: flex; align-items: center; justify-content: space-between; gap: 12px;
  padding: 12px 14px; background: #f8fafc; border-radius: 10px;
}
.list-text { font-size: 14px; color: #0f172a; font-weight: 500; flex: 1; }
.list-input {
  flex: 1; padding: 11px 12px; border: 1px solid #e2e8f0; border-radius: 8px;
  font-size: 14px; color: #0f172a; outline: none;
}
.list-input:focus { border-color: #0078D4; box-shadow: 0 0 0 3px rgba(0,120,212,0.1); }
.list-actions { display: flex; align-items: center; gap: 6px; flex-shrink: 0; }

.btn-mini {
  padding: 6px 12px; border-radius: 6px; font-size: 12px; font-weight: 600;
  border: 1px solid #e2e8f0; background: #fff; color: #475569; cursor: pointer;
  transition: all 0.15s;
}
.btn-mini:hover { background: #f1f5f9; }
.btn-save { background: #0078D4; color: #fff; border-color: #0078D4; }
.btn-save:hover { background: #005a9e; }
.btn-danger { color: #dc2626; border-color: #fca5a5; background: #fef2f2; }
.btn-danger:hover { background: #fee2e2; }

.add-row { display: flex; align-items: center; gap: 8px; }
.btn-add-item {
  padding: 11px 18px; border-radius: 8px; font-size: 13px; font-weight: 600;
  border: none; background: #0078D4; color: #fff; cursor: pointer; flex-shrink: 0;
  transition: all 0.15s;
}
.btn-add-item:hover:not(:disabled) { background: #005a9e; }
.btn-add-item:disabled { background: #94a3b8; cursor: not-allowed; }

.empty-note { font-size: 13px; color: #94a3b8; margin: 0 0 16px; font-style: italic; }

.btn {
  width: 100%; padding: 13px; border-radius: 8px; font-size: 15px; font-weight: 600;
  cursor: pointer; border: none; transition: all 0.15s;
}
.btn-primary { background: #0078D4; color: #fff; box-shadow: 0 2px 8px rgba(0,120,212,0.3); }
.btn-primary:hover:not(:disabled) { background: #005a9e; }
.btn-primary:disabled { background: #94a3b8; cursor: not-allowed; }

.message { font-size: 13px; margin-top: 12px; text-align: center; color: #059669; }
.message.error { color: #dc2626; }
</style>

// src/pages/SettingsPage.tsx
import { useState, useEffect } from 'react';
import {
  Clock,
  Bell,
  Calendar,
  FileText,
  Smartphone,
  Plus,
  Pencil,
  Trash2,
  Save,
  TriangleAlert,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Separator } from '@/components/ui/separator';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { useAuth } from '@/hooks/useAuth';
import {
  getUserSettings,
  saveUserSettings,
  getPermanentPriorities,
  addPermanentPriority,
  updatePermanentPriority,
  deletePermanentPriority,
  subscribePush,
  unsubscribePush,
  getVapidPublicKey,
  deleteAccount,
} from '@/lib/api';
import type { UserSettings, Priority } from '@/types';

const timezones = [
  { value: 'Europe/Lisbon', label: 'Europe/Lisbon (GMT+0/+1)' },
  { value: 'Europe/London', label: 'Europe/London (GMT+0/+1)' },
  { value: 'Europe/Paris', label: 'Europe/Paris (GMT+1/+2)' },
  { value: 'Europe/Berlin', label: 'Europe/Berlin (GMT+1/+2)' },
  { value: 'America/New_York', label: 'America/New_York (GMT-5/-4)' },
  { value: 'America/Chicago', label: 'America/Chicago (GMT-6/-5)' },
  { value: 'America/Los_Angeles', label: 'America/Los_Angeles (GMT-8/-7)' },
  { value: 'America/Sao_Paulo', label: 'America/Sao_Paulo (GMT-3)' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo (GMT+9)' },
  { value: 'Asia/Shanghai', label: 'Asia/Shanghai (GMT+8)' },
];

function generateTimeOptions() {
  const times = [];
  for (let h = 0; h < 24; h++) {
    for (let m = 0; m < 60; m += 30) {
      const hour = String(h).padStart(2, '0');
      const min = String(m).padStart(2, '0');
      times.push(`${hour}:${min}`);
    }
  }
  return times;
}

const timeOptions = generateTimeOptions();

const BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000';

export function SettingsPage() {
  const { email, logout } = useAuth();

  const [settings, setSettings] = useState<UserSettings>({
    digestTime: '08:00',
    reminderTime: '18:00',
    reminderEnabled: false,
    timezone: 'Europe/Lisbon',
    calendarConnected: false,
    importantSenders: [],
  });

  const [permanentPriorities, setPermanentPriorities] = useState<Priority[]>([]);
  const [newPermanent, setNewPermanent] = useState('');
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editingText, setEditingText] = useState('');

  const [importantSenders, setImportantSenders] = useState<string[]>([]);
  const [newSender, setNewSender] = useState('');

  const [pushSupported, setPushSupported] = useState(false);
  const [pushEnabled, setPushEnabled] = useState(false);

  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [isError, setIsError] = useState(false);
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [deleting, setDeleting] = useState(false);

  useEffect(() => {
    if (!email) return;

    Promise.all([
      getUserSettings(email),
      getPermanentPriorities(email),
    ]).then(([settingsData, priorities]) => {
      setSettings({
        digestTime: settingsData.digestTime || '08:00',
        reminderTime: settingsData.reminderTime || '18:00',
        reminderEnabled: settingsData.reminderEnabled || false,
        timezone: settingsData.timezone || 'Europe/Lisbon',
        calendarConnected: settingsData.calendarConnected || false,
        importantSenders: settingsData.importantSenders || [],
      });
      setImportantSenders(settingsData.importantSenders || []);
      setPermanentPriorities(priorities);
      setPushEnabled(!!settingsData.pushSubscription);
    }).catch(console.error).finally(() => setLoading(false));

    setPushSupported(
      'serviceWorker' in navigator &&
      'PushManager' in window &&
      'Notification' in window,
    );
  }, [email]);

  const handleSave = async () => {
    if (!email) return;

    setSaving(true);
    setMessage('');
    setIsError(false);

    try {
      await saveUserSettings(email, {
        ...settings,
        importantSenders,
      });
      setMessage('Settings saved!');
    } catch (e) {
      setMessage(e instanceof Error ? e.message : 'Failed to save settings');
      setIsError(true);
    } finally {
      setSaving(false);
    }
  };

  const handleAddPermanent = async () => {
    if (!email || !newPermanent.trim()) return;

    try {
      await addPermanentPriority(email, newPermanent.trim());
      setNewPermanent('');
      const priorities = await getPermanentPriorities(email);
      setPermanentPriorities(priorities);
    } catch (e) {
      setMessage(e instanceof Error ? e.message : 'Failed to add priority');
      setIsError(true);
    }
  };

  const handleSavePermanentEdit = async (id: string) => {
    if (!email || !editingText.trim()) return;

    try {
      await updatePermanentPriority(email, id, editingText.trim());
      setEditingId(null);
      setEditingText('');
      const priorities = await getPermanentPriorities(email);
      setPermanentPriorities(priorities);
    } catch (e) {
      setMessage(e instanceof Error ? e.message : 'Failed to update priority');
      setIsError(true);
    }
  };

  const handleDeletePermanent = async (id: string) => {
    if (!email) return;

    try {
      await deletePermanentPriority(email, id);
      const priorities = await getPermanentPriorities(email);
      setPermanentPriorities(priorities);
    } catch (e) {
      setMessage(e instanceof Error ? e.message : 'Failed to delete priority');
      setIsError(true);
    }
  };

  const handleAddSender = () => {
    const sender = newSender.trim().toLowerCase();
    if (!sender || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(sender)) return;
    if (importantSenders.includes(sender)) return;
    setImportantSenders([...importantSenders, sender]);
    setNewSender('');
  };

  const handleRemoveSender = (index: number) => {
    setImportantSenders(importantSenders.filter((_, i) => i !== index));
  };

  const handleEnablePush = async () => {
    if (!pushSupported || !email) return;

    try {
      const permission = await Notification.requestPermission();
      if (permission !== 'granted') {
        setMessage('Notification permission denied');
        setIsError(true);
        return;
      }

      const reg = await navigator.serviceWorker.ready;
      const vapidRes = await getVapidPublicKey();
      if (!vapidRes.publicKey) {
        setMessage('Push notifications not configured');
        setIsError(true);
        return;
      }

      const padding = '='.repeat((4 - (vapidRes.publicKey.length % 4)) % 4);
      const base64 = (vapidRes.publicKey + padding).replace(/-/g, '+').replace(/_/g, '/');
      const rawData = window.atob(base64);
      const applicationServerKey = new Uint8Array(rawData.length);
      for (let i = 0; i < rawData.length; ++i) {
        applicationServerKey[i] = rawData.charCodeAt(i);
      }

      const subscription = await reg.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: applicationServerKey.buffer,
      });

      await subscribePush(email, subscription.toJSON());
      setPushEnabled(true);
      setMessage('Push notifications enabled!');
    } catch (e) {
      setMessage(e instanceof Error ? e.message : 'Failed to enable push');
      setIsError(true);
    }
  };

  const handleDisablePush = async () => {
    if (!email) return;

    try {
      const reg = await navigator.serviceWorker.ready;
      const subscription = await reg.pushManager.getSubscription();
      if (subscription) await subscription.unsubscribe();
      await unsubscribePush(email);
      setPushEnabled(false);
      setMessage('Push notifications disabled');
    } catch (e) {
      console.error('Failed to disable push:', e);
    }
  };

  const handleDeleteAccount = async () => {
    if (!email) return;
    setDeleting(true);
    try {
      await deleteAccount(email);
      logout();
    } catch (e) {
      setDeleting(false);
      setShowDeleteDialog(false);
      setMessage(e instanceof Error ? e.message : 'Failed to delete account');
      setIsError(true);
    }
  };

  const isValidSender = /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(newSender.trim());

  const calendarConnectUrl = `${BASE_URL}/calendar/connect/${encodeURIComponent(email || '')}`;
  const icsDownloadUrl = `${BASE_URL}/calendar/ics/${encodeURIComponent(email || '')}`;

  if (loading) {
    return (
      <div className="max-w-2xl mx-auto py-8 px-4">
        <div className="animate-pulse space-y-6">
          <div className="h-8 bg-muted rounded w-48" />
          {Array.from({ length: 3 }).map((_, i) => (
            <div key={i} className="h-40 bg-muted rounded-xl" />
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto py-8 px-4 space-y-6">
      <h1 className="text-2xl font-bold text-foreground">Settings</h1>

      {/* Digest Schedule */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Clock className="w-5 h-5" />
            Digest Schedule
          </CardTitle>
          <CardDescription>
            Choose when you receive your daily email summary.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Digest Time</label>
              <Select
                value={settings.digestTime}
                onValueChange={(v) => setSettings({ ...settings, digestTime: v })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {timeOptions.map((t) => (
                    <SelectItem key={t} value={t}>{t}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Timezone</label>
              <Select
                value={settings.timezone}
                onValueChange={(v) => setSettings({ ...settings, timezone: v })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {timezones.map((tz) => (
                    <SelectItem key={tz.value} value={tz.value}>{tz.label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Daily Reminder */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Bell className="w-5 h-5" />
            Daily Reminder
          </CardTitle>
          <CardDescription>
            Get a reminder to set tomorrow's priorities.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div
            className="flex items-center justify-between p-4 bg-muted/50 rounded-lg cursor-pointer"
            onClick={() => setSettings({ ...settings, reminderEnabled: !settings.reminderEnabled })}
          >
            <div>
              <p className="text-sm font-medium">Enable daily reminder</p>
              <p className="text-xs text-muted-foreground">
                Receive a calendar event and/or push notification
              </p>
            </div>
            <div
              className={`w-11 h-6 rounded-full transition-colors ${
                settings.reminderEnabled ? 'bg-blue-600' : 'bg-slate-300'
              }`}
            >
              <div
                className={`w-5 h-5 rounded-full bg-white shadow-sm transition-transform mt-0.5 ${
                  settings.reminderEnabled ? 'translate-x-[22px]' : 'translate-x-0.5'
                }`}
              />
            </div>
          </div>

          {settings.reminderEnabled && (
            <div className="space-y-4 pt-2">
              <div className="space-y-2">
                <label className="text-sm font-medium">Reminder Time</label>
                <Select
                  value={settings.reminderTime}
                  onValueChange={(v) => setSettings({ ...settings, reminderTime: v })}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {timeOptions.map((t) => (
                      <SelectItem key={t} value={t}>{t}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-3">
                <p className="text-xs font-semibold text-muted-foreground uppercase">
                  Notification Channels
                </p>

                {/* Google Calendar */}
                <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-lg bg-blue-100 flex items-center justify-center">
                      <Calendar className="w-5 h-5 text-blue-600" />
                    </div>
                    <div>
                      <p className="text-sm font-medium">Google Calendar</p>
                      <p className="text-xs text-muted-foreground">Creates a daily calendar event</p>
                    </div>
                  </div>
                  {settings.calendarConnected ? (
                    <span className="text-xs font-medium text-emerald-600">Connected</span>
                  ) : (
                    <a href={calendarConnectUrl} className="text-xs font-medium text-blue-600 hover:underline">
                      Connect
                    </a>
                  )}
                </div>

                {/* ICS Download */}
                <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-lg bg-amber-100 flex items-center justify-center">
                      <FileText className="w-5 h-5 text-amber-600" />
                    </div>
                    <div>
                      <p className="text-sm font-medium">Apple Calendar / .ics</p>
                      <p className="text-xs text-muted-foreground">Download a file to import</p>
                    </div>
                  </div>
                  <a href={icsDownloadUrl} download className="text-xs font-medium text-slate-600 hover:underline">
                    Download .ics
                  </a>
                </div>

                {/* Push Notifications */}
                <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-lg bg-purple-100 flex items-center justify-center">
                      <Smartphone className="w-5 h-5 text-purple-600" />
                    </div>
                    <div>
                      <p className="text-sm font-medium">Push Notifications</p>
                      <p className="text-xs text-muted-foreground">Browser notification</p>
                    </div>
                  </div>
                  {pushEnabled ? (
                    <button onClick={handleDisablePush} className="text-xs font-medium text-red-600 hover:underline">
                      Disable
                    </button>
                  ) : (
                    <button
                      onClick={handleEnablePush}
                      disabled={!pushSupported}
                      className="text-xs font-medium text-blue-600 hover:underline disabled:text-slate-400"
                    >
                      {pushSupported ? 'Enable' : 'Not supported'}
                    </button>
                  )}
                </div>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Permanent Priorities */}
      <Card>
        <CardHeader>
          <CardTitle>Permanent Priorities</CardTitle>
          <CardDescription>
            These never expire and are always used to spot relevant emails.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {permanentPriorities.length > 0 && (
            <div className="space-y-2">
              {permanentPriorities.map((p) => (
                <div key={p.id} className="flex items-center gap-2 p-3 bg-muted/50 rounded-lg">
                  {editingId === p.id ? (
                    <Input
                      value={editingText}
                      onChange={(e) => setEditingText(e.target.value)}
                      onKeyDown={(e) => e.key === 'Enter' && handleSavePermanentEdit(p.id)}
                      className="flex-1"
                      autoFocus
                    />
                  ) : (
                    <span className="flex-1 text-sm">{p.rawText}</span>
                  )}
                  <div className="flex items-center gap-1">
                    {editingId === p.id ? (
                      <Button size="sm" onClick={() => handleSavePermanentEdit(p.id)}>
                        Save
                      </Button>
                    ) : (
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => {
                          setEditingId(p.id);
                          setEditingText(p.rawText);
                        }}
                      >
                        <Pencil className="w-4 h-4" />
                      </Button>
                    )}
                    <Button
                      size="sm"
                      variant="ghost"
                      className="text-destructive hover:text-destructive"
                      onClick={() => handleDeletePermanent(p.id)}
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}

          <div className="flex gap-2">
            <Input
              placeholder="e.g. Keep an eye on the bank loan"
              value={newPermanent}
              onChange={(e) => setNewPermanent(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleAddPermanent()}
            />
            <Button onClick={handleAddPermanent} disabled={!newPermanent.trim()}>
              <Plus className="w-4 h-4 mr-1" />
              Add
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Important Senders */}
      <Card>
        <CardHeader>
          <CardTitle>Important Senders</CardTitle>
          <CardDescription>
            Emails from these addresses are always flagged.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {importantSenders.length > 0 && (
            <div className="space-y-2">
              {importantSenders.map((sender, i) => (
                <div key={i} className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                  <span className="text-sm">{sender}</span>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="text-destructive hover:text-destructive"
                    onClick={() => handleRemoveSender(i)}
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>
              ))}
            </div>
          )}

          <div className="flex gap-2">
            <Input
              type="email"
              placeholder="name@company.com"
              value={newSender}
              onChange={(e) => setNewSender(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleAddSender()}
            />
            <Button onClick={handleAddSender} disabled={!isValidSender}>
              <Plus className="w-4 h-4 mr-1" />
              Add
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Save Button */}
      <Button onClick={handleSave} disabled={saving} className="w-full" size="lg">
        <Save className="w-4 h-4 mr-2" />
        {saving ? 'Saving...' : 'Save Settings'}
      </Button>

      {message && (
        <p className={`text-sm text-center ${isError ? 'text-destructive' : 'text-emerald-600'}`}>
          {message}
        </p>
      )}

      {/* Danger Zone */}
      <Card className="border-destructive/40">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-destructive">
            <TriangleAlert className="w-5 h-5" />
            Danger Zone
          </CardTitle>
          <CardDescription>
            Irreversible actions that affect your account.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-between p-4 rounded-lg border border-destructive/30 bg-destructive/5">
            <div>
              <p className="text-sm font-medium">Delete account</p>
              <p className="text-xs text-muted-foreground">
                Permanently removes your account and all associated data.
              </p>
            </div>
            <Button
              variant="destructive"
              size="sm"
              onClick={() => setShowDeleteDialog(true)}
            >
              <Trash2 className="w-4 h-4 mr-1.5" />
              Delete account
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Delete confirmation dialog */}
      <Dialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <TriangleAlert className="w-5 h-5 text-destructive" />
              Delete your account?
            </DialogTitle>
            <DialogDescription className="pt-1">
              This will permanently delete your account and all your data — priorities,
              settings, email history, and subscriptions. <strong>This cannot be undone.</strong>
            </DialogDescription>
          </DialogHeader>
          <div className="my-2 rounded-lg border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">
            Signed in as <span className="font-medium">{email}</span>
          </div>
          <DialogFooter className="gap-2 sm:gap-0">
            <Button
              variant="outline"
              onClick={() => setShowDeleteDialog(false)}
              disabled={deleting}
            >
              Cancel
            </Button>
            <Button
              variant="destructive"
              onClick={handleDeleteAccount}
              disabled={deleting}
            >
              {deleting ? 'Deleting...' : 'Yes, delete my account'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
